package entity;
// Generated Jul 12, 2014 12:42:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Sanpham generated by hbm2java
 */
@XmlRootElement
public class Sanpham  implements java.io.Serializable {


     private Integer masanpham;
     private Danhmuc danhmuc;
     private String tensanpham;
     private int gia;
     private int soluong;
     private String tinhtrang;
     private String mota;
     private Date ngaysanxuat;
     private String hinhanh;

    public Sanpham() {
    }

    public Sanpham(Danhmuc danhmuc, String tensanpham, int gia, int soluong, String tinhtrang, String mota, Date ngaysanxuat, String hinhanh) {
       this.danhmuc = danhmuc;
       this.tensanpham = tensanpham;
       this.gia = gia;
       this.soluong = soluong;
       this.tinhtrang = tinhtrang;
       this.mota = mota;
       this.ngaysanxuat = ngaysanxuat;
       this.hinhanh = hinhanh;
    }
   
    public Integer getMasanpham() {
        return this.masanpham;
    }
    
    public void setMasanpham(Integer masanpham) {
        this.masanpham = masanpham;
    }
    @XmlTransient
    public Danhmuc getDanhmuc() {
        return this.danhmuc;
    }
    
    public void setDanhmuc(Danhmuc danhmuc) {
        this.danhmuc = danhmuc;
    }
    public String getTensanpham() {
        return this.tensanpham;
    }
    
    public void setTensanpham(String tensanpham) {
        this.tensanpham = tensanpham;
    }
    public int getGia() {
        return this.gia;
    }
    
    public void setGia(int gia) {
        this.gia = gia;
    }
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Date getNgaysanxuat() {
        return this.ngaysanxuat;
    }
    
    public void setNgaysanxuat(Date ngaysanxuat) {
        this.ngaysanxuat = ngaysanxuat;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }



}


